turn off gpg sig verification throughout for the time being

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -52,8 +52,12 @@ function install_pkgs() {
   esac
 }
 
-git submodule update
-git submodule foreach git pull
+echo "> initializing, updating and pulling git submodules:"
+{
+	git submodule init 
+	git submodule update
+	git submodule foreach git pull
+} && printf "\n\n> git submodules updated!" || printf "! error updating git submodules, exiting" && exit 1
 
 # OS/Distro relevant changes
 
